# -*- coding: utf-8 -*-
"""Fasttext.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTEZNW1Nch_QdssfdoP6RZyKyxmbyGXe
"""

!pip uninstall -y numpy
!pip install numpy==1.26.4

!pip install fasttext

import fasttext

train_data = """__label__positive I love this movie it was amazing
__label__positive This product is excellent and useful
__label__positive The experience was wonderful and fantastic
__label__positive I really enjoyed the service
__label__positive The food was delicious and tasty
__label__positive This app is very good and easy to use
__label__positive The teacher explained everything clearly
__label__positive The hotel room was clean and comfortable
__label__negative I hate this movie it was terrible
__label__negative This product is very bad
__label__negative Worst experience ever
__label__negative The service was disappointing
__label__negative The food tasted awful
__label__negative This app crashes all the time
__label__negative The teacher was confusing
__label__negative The hotel room was dirty"""

with open("train.txt", "w") as file:
    file.write(train_data)

print("Training file created")

with open("train.txt", "r") as file:
    print(file.read())

import fasttext

model = fasttext.train_supervised(
    input="train.txt",
    epoch=50,
    lr=1.0,
    wordNgrams=2,
    dim=100
)

print(model.labels)

paragraph = """
I recently watched this movie with my friends.
The acting was amazing and the story was very emotional.
Every scene was interesting and enjoyable.
I would definitely recommend this movie to others.
"""

# Remove newlines
paragraph = paragraph.replace("\n", " ")

prediction = model.predict(paragraph)

print(prediction)

paragraph = """
The app keeps crashing whenever I open it.
The interface is confusing and very slow.
I had a terrible experience using this application.
"""
paragraph = paragraph.replace("\n", " ")

prediction = model.predict(paragraph)

print(prediction)

import pandas as pd
import numpy as np

df = pd.read_csv("/content/IMDB Dataset - IMDB Dataset.csv")

df

df['review'] = df['review'].str.lower()

import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

df['review'] = df['review'].apply(remove_html_tags)

def remove_url(text):
  pattern = re.compile(r'ttps?://\S+|www.\.\S+')
  return pattern.sub(r'', text)

df

df["fasttext_format"] = "__label__" + df["sentiment"] + " " + df["review"]

with open("train.txt", "w", encoding="utf-8") as f:
    for row in df["fasttext_format"]:
        f.write(row + "\n")

import fasttext

model = fasttext.train_supervised(
    input="train.txt",
    epoch=25,
    lr=1.0,
    wordNgrams=2,
    dim=100
)

model.predict("hooked")

model.predict("terrible")

model.predict("this movie was absolutely amazing")

model.predict("worst acting and terrible story")

df = df.head(1)

df.info()

df = df.copy()

df["review"] = df["review"].astype("string")
df["sentiment"] = df["sentiment"].astype("string")

df.info()

import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(df["review"][0])

for ent in doc.ents:
    print(ent.text, "->", ent.label_)

from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

doc

import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

# Apply POS tagging on review column
for review in df["review"]:
    doc = nlp(review)

    for token in doc:
        print(token.text, "---->", token.pos_)

    print("-------------------")