# -*- coding: utf-8 -*-
"""Post_tagging.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bB3-FZmV99BrKmBsGl5Pzwh9aau1zMI3
"""

## POS Tagging in NLP

#POS Tagging means Part of Speech Tagging.

#It is an NLP technique where each word in a sentence is assigned its grammatical role such as:

#Noun

#Verb

#Adjective

#Adverb

# Pronoun

#Preposition

# Conjunction

# Why POS Tagging is Important?

#POS Tagging is used in:

#Text Classification

#Chatbots

#Machine Translation

# Named Entity Recognition (NER)

#Sentiment Analysis

# Why POS Tagging is Important?

#POS Tagging is used in:

#Text Classification

# Chatbots

# Machine Translation

# Named Entity Recognition (NER)

# Sentiment Analysis

#Speech Recognition

#Grammar Checking

# Common POS Tags

# | POS Tag | Meaning |
# |---------|---------|
# |   NN    | Noun

# |   NNS   | Plural Noun

# |   NNP   | Proper Noun

# |    VB   | Verb

# |   VBD   | Verb Past Tense |

# |   VBG   | Verh Gerund

# |   JJ    |   Adjective

# |   RB    |    Adverb

# |  PRP    | Pronoun

# |   IN    | Preposition

## Working Process of POS Tagging::::

#1. Sentence is divided into tokens.

#2.NLP model checks grammar/context.

#3.Appropriate POS tag is assigned to each word.

!pip install spacy

!python -m spacy download en_core_web_sm

import spacy

#Load English model

nlp = spacy.load("en_core_web_sm")

# Input text

doc = nlp("Saurabh is learning NLP")

#POS tagging
for token in doc:
  print(token.text, "---->", token.pos_)

#Example -2

import spacy
#load model
nlp = spacy.load("en_core_web_sm")

text = "Saurabh is playing cricket"

doc = nlp(text)

for token in doc:
  print(token.text, "---->", token.pos_)

#Example -3

import spacy

nlp = spacy.load("en_core_web_sm")

text = "Saurabh is learning NLP"

doc = nlp(text)

for token in doc:
     print(
         "Word:", token.text,
         "|POS:", token.pos_,
         "|TAG:", token.tag_
     )

#visualizing POS tagging

import spacy

from spacy import displacy

nlp = spacy.load("en_core_web_sm")

text = "Saurabh is learning NLP"

doc = nlp(text)

displacy.render(doc, style="dep")

import pandas as pd
import numpy as np

df = pd.read_csv("/content/IMDB Dataset - IMDB Dataset.csv")

df

df = df.head(1)

df

df.info()

df = df.copy()

df["review"] = df["review"].astype("string")
df["sentiment"] = df["sentiment"].astype("string")

df.info()

import spacy
nlp = spacy.load("en_core_web_sm")

doc = nlp(df["review"][0])

for ent in doc.ents:
    print(ent.text, "->", ent.label_)

from spacy import displacy
displacy.render(doc, style="ent", jupyter=True)

import spacy

# Load English model
nlp = spacy.load("en_core_web_sm")

# Apply POS tagging on review column
for review in df["review"]:
    doc = nlp(review)

    for token in doc:
        print(token.text, "---->", token.pos_)

    print("-------------------")

